[package]
name = "hyperlit-model"
version = "0.1.0"
edition = "2024"
description = "A software documentation tool documentation embedded in source files - model crate"
license = "Apache-2.0"

[dependencies]
hyperlit-base = { path = "../base" }
chrono = "0.4.41"
