src_directory = "."
# Include all Rust files, but excludetest files
src_globs = ["*.rs", "!/cli/sample", "!extractor/src/extractor.rs"]
docs_directory = "docs"
doc_globs = ["*.md", "*.mdx"]
build_directory = "build"
output_directory = "output"
