[package]
name = "hyperlit"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "hyperlit"
path = "src/hyperlit-cli.rs"

[dependencies]
hyperlit-core = { path = "../core" }
hyperlit-base = { path = "../base" }
hyperlit-extractor = { path = "../extractor" }

clap = { version = "4.5.39", features = ["derive"] }
