# https://github.com/marketplace/actions/rust-release-binary
name: Build and upload relase

on:
  release:
    types: [ created ]
  workflow_dispatch:


jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          TOOLCHAIN_VERSION: stable
          SRC_DIR: cli
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          STATIC_LINKING: false # with static linking, we cannot build due to missing libz dependencies on alpine as well as the wrong openssl version being found, cf. https://github.com/marketplace/actions/rust-release-binary#static-linking